### ISSUE TITLE
Sync storage requires a static extension ID

### ISSUE THREAD

**Issue by jwlarocque** [notartom/ffreszoom#2]
Preferences are currently saved to the user's sync storage, which requires that the extension has a static ID (though the ID is no longer required in general).  Without the ID, options.js bypasses the sync storage and updates the settings in background.js directly, but the settings won't persist across sessions.

To resolve this, we could either:  

- switch to local storage, which doesn't require the ID (I think this makes sense, since users might want separate settings for different devices anyways),  
- or re-add the ID.

**Comment by notartom** [comment]
> Preferences are currently saved to the user's sync storage, which requires that the extension has a static ID (though the ID is no longer required in general). Without the ID, options.js bypasses the sync storage and updates the settings in background.js directly, but the settings won't persist across sessions.

Dammit, I should have wondered why you added it before removing it. Apologies. When I uploaded to Mozilla it complained about the ID, and I went a axed it like some sort of barbarian instead of actually trying to understand what's up.

> To resolve this, we could either:
> 
>     * switch to local storage, which doesn't require the ID (I think this makes sense, since users might want separate settings for different devices anyways),

I think this one is the better choice. The separate settings for different devices makes sense. Would that be something you'd be willing to take on? :)

>     * or re-add the ID.

**Comment by jwlarocque** [comment]
Haha I should've made a note as to why I added it.

Should be fairly simple to switch to local, I'll get that done this weekend.

**Comment by jwlarocque** [comment]
Should be resolved by PR https://github.com/notartom/ffreszoom/pull/3
